/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.service;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.example.Config;

class RegisterTest {

    private static Register register;
    
    @BeforeAll
    static void setup() {
        System.clearProperty("spring.profiles.active");
        ApplicationContext spring = 
            new AnnotationConfigApplicationContext(Config.class);
        register = spring.getBean(Register.class);        
    }

    @Test 
    void testRegister() {
        double result = register.computeTotal(100);
        Assertions.assertThat(result).isEqualTo(100.00 + 6.00);
        System.out.println(String.format("The computed total including tax is: %.2f", result));
    }

}
